name: update 

on:
  schedule:
    - cron: '0 8 * * 5'
  workflow_dispatch: 
    inputs:
      commit_message:
        description: 'Commit message'
        required: false
        default: 'chore: weekly recommit'

jobs:
  recommit:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          fetch-depth: 0

      - name: Configure Git
        run: |
          git config --local user.email "github-actions[bot]@users.noreply.github.com"
          git config --local user.name "github-actions[bot]"

      - name: Get last commit info
        id: last_commit
        run: |
          LAST_COMMIT_HASH=$(git log -1 --pretty=format:%H)
          LAST_COMMIT_MESSAGE=$(git log -1 --pretty=format:%s)
          LAST_COMMIT_DATE=$(git log -1 --pretty=format:%cd --date=format:'%Y-%m-%d %H:%M:%S')
          echo "hash=$LAST_COMMIT_HASH" >> $GITHUB_OUTPUT
          echo "message=$LAST_COMMIT_MESSAGE" >> $GITHUB_OUTPUT
          echo "date=$LAST_COMMIT_DATE" >> $GITHUB_OUTPUT

      - name: Create new commit with same changes
        run: |
          git commit --allow-empty -m "每周更新"
          
      - name: Push changes
        run: git push origin HEAD:${{ github.ref }}
